[package]
name = "raycasting"
version = "0.1.0"
edition = "2021"


[profile.dev.package."*"]
opt-level = 3


[dependencies]
minifb = "0.24.0"
rand = "0.8.5"
kira = "0.8.4"
simple_logger = { version = "4.2.0", default_features = false, features = [
    "colors",
] }
log = "0.4.19"
